name: Deploy Bicep to Azure

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main # Trigger on pushes to main branch

env:
  RESOURCE_GROUP: my-resource-group
  LOCATION: eastus
  TEMPLATE_FILE: ./firstally_IAC/template.bicep
  DEPLOYMENT_NAME: github-bicep-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Azure using service principal
      - name: Azure Login
        run: |
          az login --service-principal --username ${{ secrets.username }} --password ${{ secrets.password }} --tenant ${{ secrets.tenant }}
          az account set --subscription 'f0f3efc1-4c67-445e-a1cf-227201723279'




      # # 3. Build Bicep template
      - name: Build Bicep template
        run: |
            pwd
            ls
            az bicep build --file './firstally_IAC/template.bicep' --stdout


      # # 4. Deploy Bicep template
      - name: Deploy Bicep template
        run: |
            pwd
            ls
            az deployment tenant $(secrets.tenant)  --template-file ./firstally_IAC/template.bicep


      # 4. Logout from Azure
      - name: Azure Logout
        run: az logout
