name: Deploy Bicep to Azure

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main # Trigger on pushes to main branch

env:
  RESOURCE_GROUP: my-resource-group
  LOCATION: eastus
  TEMPLATE_FILE: ./firstally_IAC/template.bicep
  DEPLOYMENT_NAME: github-bicep-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Azure using service principal
      - name: Azure Login
        run: |
          az login --service-principal --username ${{ secrets.username }} --password ${{ secrets.password }} --tenant ${{ secrets.tenant }}
          az account set --subscription 'f0f3efc1-4c67-445e-a1cf-227201723279'


      # # 3. Deploy Bicep template
      # - name: Deploy Bicep template
      #   uses: azure/arm-deploy@v2
      #   with:
      #     scope: resourcegroup
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     resourceGroupName: ${{ env.RESOURCE_GROUP }}
      #     template: ${{ env.TEMPLATE_FILE }}
      #     deploymentName: ${{ env.DEPLOYMENT_NAME }}
      #     parameters: |
      #       location=${{ env.LOCATION }}

      # 4. Logout from Azure
      - name: Azure Logout
        run: az logout
