name: Deploy Bicep to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: my-resource-group
  LOCATION: eastus
  TEMPLATE_FILE: ./firstally_IAC/template.bicep
  DEPLOYMENT_NAME: github-bicep-deployment

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      built_file: ${{ steps.build_bicep.outputs.filepath }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.username }} \
            --password ${{ secrets.password }} \
            --tenant ${{ secrets.tenant }}
          az account set --subscription ${{ secrets.subscription_id }}

      - name: Build Bicep template
        id: build_bicep
        run: |
          mkdir -p build
          OUTPUT_FILE="build/template.json"
          az bicep build --file "${{ env.TEMPLATE_FILE }}" --outdir build
          echo "filepath=$OUTPUT_FILE" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-output
          path: build/template.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-output
          path: ./deploy

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.username }} \
            --password ${{ secrets.password }} \
            --tenant ${{ secrets.tenant }}
          az account set --subscription ${{ secrets.subscription_id }}

      - name: Deploy built ARM template
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ./deploy/template.json \
            --parameters location=${{ env.LOCATION }} \
              mariaSecretName=$(mariaSecretName) privateDNSZoneNameKeyVault=$(privateDNSZoneNameKeyVault)\
              mariaUserName=$(mariaUserName) subscriptionId=${{ secrets.subscription_id }} \

      - name: Azure Logout
        run: az logout
